### ISSUE TITLE
Verify Guess my Mood

### ISSUE THREAD

**Issue by swamisundar** [pyxeda/ML-Lessons#78]

**Comment by davidanp** [comment]
Scripts work (edge cases can make them fail though...), and the SBX files work. There are some key items missing though which have already been filed as issues.

Some breaking issues:
https://github.com/pyxeda/AiCLUB/issues/121
https://github.com/pyxeda/ML-Lessons/issues/107

The instructions are sufficient for use. But it is not an enjoyable read (which in my humble opinion, is very important for educational material). Theres tons of repetition on how to use navigator. Honestly it feels more like a manual for navigator than lesson for learning ML. The extent of learning for ML, is lower than I expected. The amount of learning was similar to vocabulary instead of problem solving (which could be a good start for beginners. you got to learn the language before doing more anyways).
